application: focusbot-hrd
version: 1
runtime: python27
api_version: 1
threadsafe: true

handlers:
- url: /static
  static_dir: static

- url: /.*
  script: gae.APPLICATION

inbound_services:
- xmpp_message
- xmpp_presence

libraries:
- name: jinja2
  version: latest